#include "EffectColor.h"

#define COLOR_HIGH 0.9
#define COLOR_LOW 0.1

#define COLORKEY_HIGH 1.0
#define COLORKEY_LOW 0.2

const Color breakColor16[16]
{
	{COLOR_LOW,COLOR_LOW,COLOR_LOW,1},
	{COLOR_HIGH,COLOR_LOW,COLOR_LOW,1},
	{COLOR_HIGH,COLOR_LOW,COLOR_LOW,1},
	{COLOR_HIGH,COLOR_LOW,COLOR_HIGH,1},
	{COLOR_HIGH,COLOR_LOW,COLOR_HIGH,1},
	{COLOR_LOW,COLOR_LOW,COLOR_HIGH,1},
	{COLOR_LOW,COLOR_LOW,COLOR_HIGH,1},
	{COLOR_LOW,COLOR_HIGH,COLOR_HIGH,1},
	{COLOR_LOW,COLOR_HIGH,COLOR_HIGH,1},
	{COLOR_LOW,COLOR_HIGH,COLOR_LOW,1},
	{COLOR_LOW,COLOR_HIGH,COLOR_LOW,1},
	{COLOR_LOW,COLOR_HIGH,COLOR_LOW,1},
	{COLOR_HIGH,COLOR_HIGH,COLOR_LOW,1},
	{COLOR_HIGH,COLOR_HIGH,COLOR_LOW,1},
	{COLOR_HIGH,COLOR_HIGH,COLOR_LOW,1},
	{COLOR_LOW,COLOR_LOW,COLOR_LOW,1}
};

const Color breakColor8[8]
{
	{COLOR_LOW,COLOR_LOW,COLOR_LOW,1},
	{COLOR_HIGH,COLOR_LOW,COLOR_LOW,1},
	{COLOR_HIGH,COLOR_LOW,COLOR_HIGH,1},
	{COLOR_LOW,COLOR_LOW,COLOR_HIGH,1},
	{COLOR_LOW,COLOR_HIGH,COLOR_HIGH,1},
	{COLOR_LOW,COLOR_HIGH,COLOR_LOW,1},
	{COLOR_HIGH,COLOR_HIGH,COLOR_LOW,1},
	{COLOR_LOW,COLOR_LOW,COLOR_LOW,1}
};

const Color breakColor4[4]
{
	{COLOR_HIGH,COLOR_LOW,COLOR_LOW,1},
	{COLOR_LOW,COLOR_LOW,COLOR_HIGH,1},
	{COLOR_LOW,COLOR_HIGH,COLOR_LOW,1},
	{COLOR_HIGH,COLOR_HIGH,COLOR_LOW,1}
};

const Color breakColorYanDan[4]
{
	{COLOR_HIGH,COLOR_LOW,COLOR_LOW,1},
	{COLOR_HIGH,COLOR_LOW,COLOR_HIGH,1},
	{COLOR_LOW,COLOR_LOW,COLOR_HIGH,1},
	{COLOR_HIGH,COLOR_HIGH,COLOR_LOW,1}
};

const Color auraColorKey[6]
{
	{COLORKEY_LOW,COLORKEY_HIGH,COLORKEY_HIGH,1},
	{COLORKEY_HIGH,COLORKEY_LOW,COLORKEY_HIGH,1},
	{COLORKEY_HIGH,COLORKEY_HIGH,COLORKEY_LOW,1},
	{COLORKEY_LOW,COLORKEY_LOW,COLORKEY_HIGH,1},
	{COLORKEY_LOW,COLORKEY_HIGH,COLORKEY_LOW,1},
	{COLORKEY_HIGH,COLORKEY_LOW,COLORKEY_LOW,1}
};

const int bulletFog1Index16[16]
{
	0,1,1,2,2,3,3,4,4,5,5,5,6,6,6,7
};

const int bulletFog1Index8[8]
{
	0,1,2,3,4,5,6,7
};

const int bulletFog1Index4[4]
{
	1,3,5,6
};

const int bulletFog1IndexYanDan[4]
{
	1,2,3,6
};